import test from "node:test";
import assert from "node:assert/strict";
import { dom } from "./dom-mock.ts";
import "./indexeddb-mock.ts";

test.after(() => dom.window.close());

(globalThis as any).localStorage = {
  store: {} as Record<string, string>,
  getItem(key: string) { return this.store[key] || null; },
  setItem(key: string, value: string) { this.store[key] = String(value); },
  removeItem(key: string) { delete this.store[key]; },
  clear() { this.store = {}; }
};

import { setAppState } from "../src/state/state.ts";
import { addDistributionRow } from "../src/activities/distribution-rows.ts";

function baseState(overrides: any = {}) {
  return {
    settings: {
      theme: "dark",
      rooms: [],
      departments: [],
      accounts: [
        { code: "892-1", description: "Location de salles" },
        { code: "892-2", description: "Services" }
      ],
      last_backup_date: "",
      backup_reminder_days: 7,
      salaries: [],
      services: [],
      global_tasks: [],
      schedulable_tasks: []
    },
    activities: [],
    favorites: [],
    selected_year: "2025-2026",
    selected_quarters: [1, 2, 3, 4],
    ...overrides
  };
}

test.beforeEach(() => {
  setAppState(baseState());
  // Stub the fields autoSaveActivityForm() reads: an empty internal id makes it return
  // immediately, so wiring the row's listeners doesn't require the whole activity form.
  document.body.innerHTML = `
    <input id="form-activity-internal-id" value="">
    <div id="form-distribution-list"></div>
  `;
});

test("addDistributionRow appends a row pre-filled with the given account/amount/reference/details", () => {
  addDistributionRow("892-1", 150, "RI-42", "Détails du versement");

  const row = document.querySelector("#form-distribution-list .distribution-row") as HTMLElement;
  assert.ok(row);
  assert.equal(row.querySelector<HTMLInputElement>(".dist-amount-input")!.value, "150");
  assert.equal(row.querySelector<HTMLInputElement>(".dist-reference-input")!.value, "RI-42");
  assert.equal(row.querySelector<HTMLInputElement>(".dist-details-input")!.value, "Détails du versement");
  assert.equal(row.querySelector<HTMLInputElement>(".dist-account-select-wrapper .searchable-select-value")!.value, "892-1");
});

test("addDistributionRow leaves the amount input blank rather than showing 0 when amount is 0", () => {
  addDistributionRow();
  const row = document.querySelector("#form-distribution-list .distribution-row") as HTMLElement;
  assert.equal(row.querySelector<HTMLInputElement>(".dist-amount-input")!.value, "");
});

test("addDistributionRow shows the 'Généré' badge only when autoGenerated is true", () => {
  addDistributionRow("892-1", 100, "", "", true);
  const row = document.querySelector("#form-distribution-list .distribution-row") as HTMLElement;
  assert.equal(row.dataset.autoGenerated, "1");
  assert.ok(row.querySelector(".badge-auto"));
});

test("addDistributionRow's account select is populated with every configured GL account", () => {
  addDistributionRow();
  const row = document.querySelector("#form-distribution-list .distribution-row") as HTMLElement;
  const options = row.querySelectorAll(".dist-account-select-wrapper .searchable-select-option");
  // The results panel only renders once opened/filtered; querying the wired items directly
  // via the input's typed-search behaviour is simpler: type nothing and trigger focus.
  const input = row.querySelector<HTMLInputElement>(".dist-account-select-wrapper .searchable-select-input")!;
  input.dispatchEvent(new (globalThis as any).Event("focus", { bubbles: true }));
  const opts = Array.from(row.querySelectorAll(".dist-account-select-wrapper .searchable-select-option")).map(o => o.textContent);
  assert.ok(opts.some(t => t?.includes("892-1")));
  assert.ok(opts.some(t => t?.includes("892-2")));
});

test("addDistributionRow's delete button removes the row from the DOM", () => {
  addDistributionRow("892-1", 100);
  assert.equal(document.querySelectorAll("#form-distribution-list .distribution-row").length, 1);

  const delBtn = document.querySelector(".delete-dist-row-btn") as HTMLElement;
  delBtn.dispatchEvent(new (globalThis as any).Event("click", { bubbles: true }));

  assert.equal(document.querySelectorAll("#form-distribution-list .distribution-row").length, 0);
});

test("adding several rows keeps each one's inputs independently addressable", () => {
  addDistributionRow("892-1", 100, "RI-1");
  addDistributionRow("892-2", 200, "RI-2");

  const rows = document.querySelectorAll("#form-distribution-list .distribution-row");
  assert.equal(rows.length, 2);
  assert.equal((rows[0].querySelector(".dist-reference-input") as HTMLInputElement).value, "RI-1");
  assert.equal((rows[1].querySelector(".dist-reference-input") as HTMLInputElement).value, "RI-2");
});

export {};
