/**
 * activities-distribution-rows.ts - Adds a GL distribution row to the activity form.
 * Split out of activities-financials.ts (see that file for the rest of the module's history).
 */
import { getAccounts } from "../state/settings-repository.ts";
import {
  escapeHtml,
  buildSearchableSelectHtml,
  initSearchableSelectEl,
  rejectNegativeAmountOnBlur,
  elById,
  debounce
} from "../utils/utils.ts";
import { updateDistributionTotal } from "./financial-summary.ts";
import { autoSaveActivityForm } from "./autosave.ts";

function addDistributionRow(accountCode = "", amount = 0, reference = "", details = "", autoGenerated = false) {
  const container = elById("form-distribution-list");
  const rowId = "dist-row-" + Date.now() + Math.random().toString(36).substr(2, 5);

  const rowHtml = `
    <div id="${rowId}" class="distribution-row" data-auto-generated="${autoGenerated ? "1" : ""}" style="grid-template-columns: 1.3fr 0.8fr 1fr 1.3fr auto auto; align-items: center;">
      ${buildSearchableSelectHtml("dist-account-select-wrapper", "dist-account-select", "Choisir un compte...", `${rowId}-account`)}
      <input type="number" id="${rowId}-amount" class="form-input dist-amount-input" min="0" step="0.01" value="${amount > 0 ? amount : ""}" placeholder="Montant $" style="padding: 8px 12px; font-size: 0.85rem;">
      <input type="text" id="${rowId}-reference" class="form-input dist-reference-input" value="${escapeHtml(reference)}" placeholder="N° Facture, RI ou Encaissement" style="padding: 8px 12px; font-size: 0.85rem;">
      <input type="text" id="${rowId}-details" class="form-input dist-details-input" value="${escapeHtml(details)}" placeholder="Détails" style="padding: 8px 12px; font-size: 0.85rem;">
      <div style="display: flex; align-items: center; justify-content: center; min-width: 50px;">
        ${autoGenerated ? `<span class="badge badge-auto" style="white-space: nowrap;" title="Généré automatiquement par l'application">Généré</span>` : ""}
      </div>
      <button type="button" class="btn-icon delete-dist-row-btn" data-row-id="${rowId}">
        <svg viewBox="0 0 24 24" style="width: 14px; height: 14px;"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
      </button>
    </div>
  `;

  container.insertAdjacentHTML("beforeend", rowHtml);

  // Attach listeners
  const newRow = elById(rowId);
  newRow.querySelector(".delete-dist-row-btn")!.addEventListener("click", () => {
    const amt = parseFloat(newRow.querySelector<HTMLInputElement>(".dist-amount-input")!.value) || 0;
    const acc = newRow.querySelector<HTMLInputElement>(".dist-account-select-wrapper .searchable-select-value")?.value || "";
    const hasContent = amt > 0 || !!acc;
    if (hasContent && !confirm("Retirer cette ligne de répartition ?")) return;
    newRow.remove();
    updateDistributionTotal();
    autoSaveActivityForm();
  });

  const glItems = getAccounts().map(acc => ({
    value: acc.code,
    label: `${acc.code} (${acc.description})`
  }));

  initSearchableSelectEl(
    newRow.querySelector<HTMLElement>(".dist-account-select-wrapper")!,
    glItems,
    value => {
      autoSaveActivityForm();
    },
    accountCode
  );

  newRow.querySelector(".dist-amount-input")!.addEventListener("input", debounce(updateDistributionTotal, 250));
  newRow.querySelector(".dist-amount-input")!.addEventListener("change", () => updateDistributionTotal());
  rejectNegativeAmountOnBlur(newRow.querySelector<HTMLInputElement>(".dist-amount-input")!);

  updateDistributionTotal();
}

export { addDistributionRow };
