/**
 * "Planification" tab: the task checklist (add/remove/check rows), auto-generation of tasks from
 * the activity's rooms/global tasks/schedulable tasks, and progress display. Split out of
 * activities-form.ts (activity drawer form wiring).
 */
import { appState, activityMatchesTask } from "../state/state.ts";
import { generateUid, escapeHtml, getReservationRoomLabel, OTHER_ROOM_VALUE, debounce } from "../utils/utils.ts";
import { getPlanningProgress, buildProgressBarHtml } from "./render.ts";
import { commitActivityPatch } from "./form-state-bar.ts";
import { deriveActivityState } from "./render.ts";

// Typed shorthand for document.getElementById — see activities-financials.ts's `el` helper doc
// comment for why this cast is needed/safe.
function el<T extends Element = HTMLInputElement>(id: string): T {
  return document.getElementById(id) as unknown as T;
}

export function renderPlanningTab(act: any) {
  el("planning-tasks-list").innerHTML = "";
  (act.planning_tasks || []).forEach((t: any) => addPlanningTaskRow(t));
  updatePlanningProgressDisplay(act);
  el("generate-planning-tasks-btn").disabled = (act.planning_tasks || []).length > 0;
}

export function addPlanningTaskRow(task: any) {
  const container = el("planning-tasks-list");
  const rowId = generateUid("task-row");
  const doneStyle = task.done ? "text-decoration: line-through; color: var(--text-muted);" : "";

  container.insertAdjacentHTML(
    "beforeend",
    `
    <div id="${rowId}" class="distribution-row" data-task-id="${escapeHtml(task.id)}" data-auto-generated="${task.auto_generated ? "1" : ""}" data-auto-generated-reason="${escapeHtml(task.auto_generated_reason || "")}" style="grid-template-columns: auto 1fr auto auto; align-items: center;">
      <input type="checkbox" id="${rowId}-done" class="task-done-checkbox" ${task.done ? "checked" : ""}>
      <input type="text" id="${rowId}-desc" class="form-input task-desc-input" value="${escapeHtml(task.description)}" placeholder="Description de la tâche" style="padding: 8px 12px; font-size: 0.85rem; ${doneStyle}">
      <div style="display: flex; align-items: center; justify-content: center; min-width: 50px;">
        ${task.auto_generated ? `<span class="badge badge-auto" style="white-space: nowrap;" title="${escapeHtml(task.auto_generated_reason || "Généré automatiquement par l'application")}">Généré</span>` : ""}
      </div>
      <button type="button" class="btn-icon delete-task-row-btn" data-row-id="${rowId}">
        <svg viewBox="0 0 24 24" style="width: 14px; height: 14px;"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
      </button>
    </div>
  `
  );

  const row = el(rowId);
  const descInput = row.querySelector<HTMLInputElement>(".task-desc-input")!;
  const checkbox = row.querySelector<HTMLInputElement>(".task-done-checkbox")!;

  row.querySelector(".delete-task-row-btn")!.addEventListener("click", () => {
    row.remove();
    persistPlanningTasks();
  });
  checkbox.addEventListener("change", () => {
    descInput.style.textDecoration = checkbox.checked ? "line-through" : "none";
    descInput.style.color = checkbox.checked ? "var(--text-muted)" : "";
    persistPlanningTasks();
  });
  descInput.addEventListener("input", debounce(persistPlanningTasks, 500));
  descInput.addEventListener("change", persistPlanningTasks);
}

function collectPlanningTasksFromForm() {
  return Array.from(document.querySelectorAll<HTMLElement>("#planning-tasks-list .distribution-row"))
    .map(row => ({
      id: row.dataset.taskId || generateUid("task"),
      description: row.querySelector<HTMLInputElement>(".task-desc-input")!.value.trim(),
      done: row.querySelector<HTMLInputElement>(".task-done-checkbox")!.checked,
      auto_generated: row.dataset.autoGenerated === "1",
      auto_generated_reason: row.dataset.autoGeneratedReason || undefined
    }))
    .filter(t => t.description);
}

function updatePlanningProgressDisplay(act: any) {
  const progress = getPlanningProgress(act);
  el("planning-progress-bar-container").innerHTML = buildProgressBarHtml(progress.percent);
  el("planning-progress-label").textContent =
    progress.total > 0 ? `${progress.done}/${progress.total} tâches (${progress.percent}%)` : "Aucune tâche";
}

// Persists the current task list immediately (planning is a live checklist, not gated behind
// the main "Enregistrer" button) and auto-advances the state to Planifiée once every task is
// done — but never downgrades a state that has already moved past Planifiée.
function persistPlanningTasks() {
  const id = el("form-activity-internal-id").value;
  if (!id) return;
  const tasks = collectPlanningTasksFromForm();

  commitActivityPatch(id, (act: any) => {
    act.planning_tasks = tasks;
    act.state = deriveActivityState(act);
  });

  const updated = appState.activities.find((a: any) => a.id === id);
  if (updated) {
    updatePlanningProgressDisplay(updated);
    el("generate-planning-tasks-btn").disabled = (updated.planning_tasks || []).length > 0;
  }
}

// Derives the planning checklist from the Soumission tab's data: one room-reservation task per
// réservation (naming any linked rooms that come along with it), a personnel-reservation task per
// réservation that has staff attached, one task per linked "tâche du gestionnaire" on that room's
// config, one task per configured global task (Configuration > Tâches globales), and one task per
// configured schedulable task (Configuration > Tâches programmables) whose conditions match this
// activity.
export function generatePlanningTasks(act: any) {
  if ((act.planning_tasks || []).length > 0) return;

  const tasks: any[] = [];
  (act.reservations || []).forEach((r: any) => {
    const roomLabel = getReservationRoomLabel(r);
    const roomConfig = r.room_name === OTHER_ROOM_VALUE ? null : appState.settings.rooms.find((rc: any) => rc.name === r.room_name);
    const linkedNames = roomConfig ? roomConfig.linked_rooms || [] : [];
    const reserveDesc = linkedNames.length
      ? `Réserver la salle ${roomLabel} (et salles liées : ${linkedNames.join(", ")}) dans le logiciel officiel`
      : `Réserver la salle ${roomLabel} dans le logiciel officiel`;
    tasks.push({
      id: generateUid("task"),
      description: reserveDesc,
      done: false,
      auto_generated: true,
      auto_generated_reason: `Généré à partir de la réservation de la salle ${roomLabel}`
    });

    const hasStaffForRoom = (r.staff || []).length > 0;
    if (hasStaffForRoom) {
      tasks.push({
        id: generateUid("task"),
        description: `Réserver le personnel pour ${roomLabel}`,
        done: false,
        auto_generated: true,
        auto_generated_reason: `Généré à partir du personnel réservé pour la salle ${roomLabel}`
      });
    }

    (roomConfig ? roomConfig.linked_tasks || [] : []).forEach((lt: any) => {
      tasks.push({
        id: generateUid("task"),
        description: lt.description,
        done: false,
        auto_generated: true,
        auto_generated_reason: `Généré à partir des tâches du gestionnaire configurées pour la salle ${roomLabel}`
      });
    });
  });

  (appState.settings.global_tasks || []).forEach((gt: any) => {
    tasks.push({
      id: generateUid("task"),
      description: gt.description,
      done: false,
      auto_generated: true,
      auto_generated_reason: "Généré à partir des tâches globales"
    });
  });

  (appState.settings.schedulable_tasks || []).forEach((st: any) => {
    if (activityMatchesTask(act, st)) {
      tasks.push({
        id: generateUid("task"),
        description: st.description,
        done: false,
        auto_generated: true,
        auto_generated_reason: "Généré à partir des tâches programmables"
      });
    }
  });

  commitActivityPatch(act.id, (a: any) => {
    a.planning_tasks = tasks;
  });
  renderPlanningTab(appState.activities.find((a: any) => a.id === act.id));
}
