import { appState, getActiveSalaryRate, getActiveSalaryOvertimeRate, getActiveServiceRate } from "../state/state.ts";
import {
  escapeHtml,
  formatCurrency,
  generateUid,
  buildGlAccountOptionsHtml,
  buildSearchableSelectHtml,
  initSearchableSelectEl,
  rejectNegativeAmountOnBlur
} from "../utils/utils.ts";
import { updateSubmissionFinancialSummary, autoSaveActivityForm } from "./financials.ts";

function el<T extends Element = HTMLInputElement>(id: string): T {
  return document.getElementById(id) as unknown as T;
}

// Helper to query DOM for the earliest slot date to avoid circular dependency
// with activities-reservations.ts's collectReservationsFromForm()
function getEarliestSlotDateFromDom(): string {
  const dates = Array.from(document.querySelectorAll<HTMLInputElement>(".slot-date-input"))
    .map(el => el.value)
    .filter(Boolean)
    .sort();
  return dates[0] || "";
}

// Builds the "Tarif" options shared by services and salaries: each a named price point (with its
// own budget account) configured in the Équipements/Salaires settings, e.g. one for internal
// clients, one for external ones. Falls back to a single "Aucun" option when none are configured.
function buildTarifOptionsHtml(
  entity: { tarifs?: { id: string; label: string; gl_account_code: string }[] } | undefined,
  selectedTarifId = ""
): string {
  if (!entity) {
    return '<option value="">Aucun</option>';
  }
  const tarifs = entity.tarifs || [];
  let html = tarifs
    .map(t => {
      const label = t.label ? `${t.label} (${t.gl_account_code})` : t.gl_account_code || "(sans compte)";
      return `<option value="${t.id}" ${t.id === selectedTarifId ? "selected" : ""}>${escapeHtml(label)}</option>`;
    })
    .join("");
  html += `<option value="__custom__" ${selectedTarifId === "__custom__" ? "selected" : ""}>Montant personnalisé...</option>`;
  return html;
}

export function addStaffRow(
  container: HTMLElement,
  salaryId = "",
  count = 1,
  hours = 0,
  overtimeHours = 0,
  tarifId = "",
  autoGenerated = false,
  customRate = 0,
  customOvertimeRate = 0,
  customGlAccountCode = ""
) {
  const rowId = generateUid("staff-row");
  const wrapperId = rowId + "-wrapper";
  const isCustom = tarifId === "__custom__";

  const salaryOptionsHtml = (appState.settings.salaries || [])
    .map(s => `<option value="${s.id}" ${s.id === salaryId ? "selected" : ""}>${s.job}</option>`)
    .join("");
  const initialSalary = (appState.settings.salaries || []).find(s => s.id === salaryId);

  container.insertAdjacentHTML(
    "beforeend",
    `
    <div id="${wrapperId}" class="distribution-row-wrapper" data-auto-generated="${autoGenerated ? "1" : ""}" style="margin-bottom: 8px; width: 100%;">
      <div id="${rowId}" class="distribution-row" style="grid-template-columns: 1.2fr 0.6fr 0.6fr 0.6fr 1fr 1fr 50px 38px; align-items: center;">
        <select id="${rowId}-salary" class="select-input staff-salary-select" style="padding: 8px 12px; font-size: 0.85rem;">
          <option value="">Choisir un emploi...</option>
          ${salaryOptionsHtml}
        </select>
        <input type="number" id="${rowId}-count" class="form-input staff-count-input" min="1" step="1" value="${count || 1}" placeholder="Qté" style="padding: 8px 12px; font-size: 0.85rem;">
        <input type="number" id="${rowId}-hours" class="form-input staff-hours-input" min="0" step="0.25" value="${hours || 0}" placeholder="Heures" style="padding: 8px 12px; font-size: 0.85rem;">
        <input type="number" id="${rowId}-overtime-hours" class="form-input staff-overtime-hours-input" min="0" step="0.25" value="${overtimeHours || 0}" placeholder="Heures sup." title="Heures en temps supplémentaire" style="padding: 8px 12px; font-size: 0.85rem;">
        <select id="${rowId}-tarif" class="select-input staff-tarif-select" title="Tarif à facturer" style="padding: 8px 12px; font-size: 0.85rem;">
          ${buildTarifOptionsHtml(initialSalary, tarifId)}
        </select>
        <span class="staff-subtotal-display" style="font-size: 0.85rem; color: var(--text-secondary); align-self: center;">0,00 $</span>
        <div style="display: flex; align-items: center; justify-content: center; min-width: 50px;">
          ${autoGenerated ? `<span class="badge badge-auto" style="white-space: nowrap;" title="Généré automatiquement par l'application">Généré</span>` : ""}
        </div>
        <button type="button" class="btn-icon delete-staff-row-btn" data-row-id="${rowId}">
          <svg viewBox="0 0 24 24" style="width: 14px; height: 14px;"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
        </button>
      </div>
      <div class="staff-custom-fields" style="display: ${isCustom ? "grid" : "none"}; grid-template-columns: 1fr 1fr 1.5fr; gap: 12px; padding: 10px 12px; margin-top: 4px; background: rgba(255, 255, 255, 0.02); border-left: 3px solid var(--primary); border-radius: 0 4px 4px 0;">
        <div class="form-group" style="margin-bottom: 0;">
          <label style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase; margin-bottom: 4px; display: block;">Taux régulier personnalisé ($/h)</label>
          <input type="number" class="form-input staff-custom-rate-input" min="0" step="0.01" value="${customRate > 0 ? customRate : ""}" placeholder="0,00" style="padding: 6px 10px; font-size: 0.8rem;">
        </div>
        <div class="form-group" style="margin-bottom: 0;">
          <label style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase; margin-bottom: 4px; display: block;">Taux supplémentaire ($/h)</label>
          <input type="number" class="form-input staff-custom-overtime-rate-input" min="0" step="0.01" value="${customOvertimeRate > 0 ? customOvertimeRate : ""}" placeholder="0,00" style="padding: 6px 10px; font-size: 0.8rem;">
        </div>
        <div class="form-group" style="margin-bottom: 0;">
          <label style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase; margin-bottom: 4px; display: block;">Code budgétaire</label>
          <select class="select-input staff-custom-gl-select" style="padding: 6px 10px; font-size: 0.8rem; width: 100%;">
            ${buildGlAccountOptionsHtml(customGlAccountCode)}
          </select>
        </div>
      </div>
    </div>
    `
  );

  const wrapper = el(wrapperId);
  const row = el(rowId);
  const customFields = wrapper.querySelector<HTMLElement>(".staff-custom-fields")!;
  const tarifSelect = row.querySelector<HTMLSelectElement>(".staff-tarif-select")!;

  row.querySelector<HTMLInputElement>(".delete-staff-row-btn")!.addEventListener("click", () => {
    wrapper.remove();
    updateSubmissionFinancialSummary();
    autoSaveActivityForm();
  });

  row.querySelector<HTMLSelectElement>(".staff-salary-select")!.addEventListener("change", e => {
    const salary = (appState.settings.salaries || []).find(s => s.id === (e.target as HTMLSelectElement).value);
    tarifSelect.innerHTML = buildTarifOptionsHtml(salary);
    customFields.style.display = tarifSelect.value === "__custom__" ? "grid" : "none";
  });

  tarifSelect.addEventListener("change", () => {
    const isCustomActive = tarifSelect.value === "__custom__";
    customFields.style.display = isCustomActive ? "grid" : "none";
    updateSubmissionFinancialSummary();
    autoSaveActivityForm();
  });

  wrapper.querySelectorAll<HTMLInputElement>("select, input")!.forEach(el => {
    el.addEventListener("input", updateSubmissionFinancialSummary);
    el.addEventListener("change", updateSubmissionFinancialSummary);
  });
  rejectNegativeAmountOnBlur(wrapper.querySelector<HTMLInputElement>(".staff-custom-rate-input")!);
  rejectNegativeAmountOnBlur(wrapper.querySelector<HTMLInputElement>(".staff-custom-overtime-rate-input")!);

  updateStaffRowSubtotal(row);
}

export function updateStaffRowSubtotal(row: HTMLElement) {
  const salaryId = row.querySelector<HTMLInputElement>(".staff-salary-select")!.value;
  const tarifId = row.querySelector<HTMLInputElement>(".staff-tarif-select")!.value;
  const count = parseInt(row.querySelector<HTMLInputElement>(".staff-count-input")!.value, 10) || 0;
  const hours = parseFloat(row.querySelector<HTMLInputElement>(".staff-hours-input")!.value) || 0;
  const overtimeHours = parseFloat(row.querySelector<HTMLInputElement>(".staff-overtime-hours-input")!.value) || 0;
  const salary = (appState.settings.salaries || []).find(s => s.id === salaryId);
  const dateStr = getEarliestSlotDateFromDom();

  let rate = 0;
  let overtimeRate = 0;
  if (tarifId === "__custom__") {
    const wrapper = row.closest(".distribution-row-wrapper");
    rate = wrapper ? parseFloat(wrapper.querySelector<HTMLInputElement>(".staff-custom-rate-input")!.value) || 0 : 0;
    overtimeRate = wrapper ? parseFloat(wrapper.querySelector<HTMLInputElement>(".staff-custom-overtime-rate-input")!.value) || 0 : 0;
  } else {
    rate = salary ? getActiveSalaryRate(salary, dateStr, tarifId) : 0;
    overtimeRate = salary ? getActiveSalaryOvertimeRate(salary, dateStr, tarifId) : 0;
  }

  row.querySelector<HTMLInputElement>(".staff-subtotal-display")!.textContent = formatCurrency(
    rate * hours * count + overtimeRate * overtimeHours * count
  );
}

export function addServiceRow(
  container: HTMLElement,
  serviceId = "",
  count = 1,
  hours = 0,
  tarifId = "",
  autoGenerated = false,
  customRate = 0,
  customGlAccountCode = ""
) {
  const rowId = generateUid("service-row");
  const wrapperId = rowId + "-wrapper";
  const isCustom = tarifId === "__custom__";

  const serviceOptionsHtml = (appState.settings.services || [])
    .map(s => `<option value="${s.id}" ${s.id === serviceId ? "selected" : ""}>${s.name}</option>`)
    .join("");
  const initialService = (appState.settings.services || []).find(s => s.id === serviceId);

  container.insertAdjacentHTML(
    "beforeend",
    `
    <div id="${wrapperId}" class="distribution-row-wrapper" data-auto-generated="${autoGenerated ? "1" : ""}" style="margin-bottom: 8px; width: 100%;">
      <div id="${rowId}" class="distribution-row" style="grid-template-columns: 1.3fr 0.6fr 0.6fr 1fr 1fr 50px 38px; align-items: center;">
        <select id="${rowId}-service" class="select-input service-select" style="padding: 8px 12px; font-size: 0.85rem;">
          <option value="">Choisir un équipement...</option>
          ${serviceOptionsHtml}
        </select>
        <input type="number" id="${rowId}-count" class="form-input service-count-input" min="1" step="1" value="${count || 1}" placeholder="Qté" style="padding: 8px 12px; font-size: 0.85rem;">
        <input type="number" id="${rowId}-hours" class="form-input service-hours-input" min="0" step="0.25" value="${hours || 0}" placeholder="Heures" style="padding: 8px 12px; font-size: 0.85rem;">
        <select id="${rowId}-tarif" class="select-input service-tarif-select" title="Tarif à facturer" style="padding: 8px 12px; font-size: 0.85rem;">
          ${buildTarifOptionsHtml(initialService, tarifId)}
        </select>
        <span class="service-subtotal-display" style="font-size: 0.85rem; color: var(--text-secondary); align-self: center;">0,00 $</span>
        <div style="display: flex; align-items: center; justify-content: center; min-width: 50px;">
          ${autoGenerated ? `<span class="badge badge-auto" style="white-space: nowrap;" title="Généré automatiquement par l'application">Généré</span>` : ""}
        </div>
        <button type="button" class="btn-icon delete-service-row-btn" data-row-id="${rowId}">
          <svg viewBox="0 0 24 24" style="width: 14px; height: 14px;"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
        </button>
      </div>
      <div class="service-custom-fields" style="display: ${isCustom ? "grid" : "none"}; grid-template-columns: 1fr 1.5fr; gap: 12px; padding: 10px 12px; margin-top: 4px; background: rgba(255, 255, 255, 0.02); border-left: 3px solid var(--primary); border-radius: 0 4px 4px 0;">
        <div class="form-group" style="margin-bottom: 0;">
          <label style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase; margin-bottom: 4px; display: block;">Tarif personnalisé ($)</label>
          <input type="number" class="form-input service-custom-rate-input" min="0" step="0.01" value="${customRate > 0 ? customRate : ""}" placeholder="0,00" style="padding: 6px 10px; font-size: 0.8rem;">
        </div>
        <div class="form-group" style="margin-bottom: 0;">
          <label style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase; margin-bottom: 4px; display: block;">Code budgétaire</label>
          <select class="select-input service-custom-gl-select" style="padding: 6px 10px; font-size: 0.8rem; width: 100%;">
            ${buildGlAccountOptionsHtml(customGlAccountCode)}
          </select>
        </div>
      </div>
    </div>
    `
  );

  const wrapper = el(wrapperId);
  const row = el(rowId);
  const customFields = wrapper.querySelector<HTMLElement>(".service-custom-fields")!;
  const tarifSelect = row.querySelector<HTMLSelectElement>(".service-tarif-select")!;

  row.querySelector<HTMLInputElement>(".delete-service-row-btn")!.addEventListener("click", () => {
    wrapper.remove();
    updateSubmissionFinancialSummary();
    autoSaveActivityForm();
  });

  row.querySelector<HTMLSelectElement>(".service-select")!.addEventListener("change", e => {
    const service = (appState.settings.services || []).find(s => s.id === (e.target as HTMLSelectElement).value);
    tarifSelect.innerHTML = buildTarifOptionsHtml(service);
    customFields.style.display = tarifSelect.value === "__custom__" ? "grid" : "none";
  });

  tarifSelect.addEventListener("change", () => {
    const isCustomActive = tarifSelect.value === "__custom__";
    customFields.style.display = isCustomActive ? "grid" : "none";
    updateSubmissionFinancialSummary();
    autoSaveActivityForm();
  });

  wrapper.querySelectorAll<HTMLInputElement>("select, input")!.forEach(el => {
    el.addEventListener("input", updateSubmissionFinancialSummary);
    el.addEventListener("change", updateSubmissionFinancialSummary);
  });
  rejectNegativeAmountOnBlur(wrapper.querySelector<HTMLInputElement>(".service-custom-rate-input")!);

  updateServiceRowSubtotal(row);
}

export function updateServiceRowSubtotal(row: HTMLElement) {
  const serviceId = row.querySelector<HTMLInputElement>(".service-select")!.value;
  const tarifId = row.querySelector<HTMLInputElement>(".service-tarif-select")!.value;
  const count = parseInt(row.querySelector<HTMLInputElement>(".service-count-input")!.value, 10) || 0;
  const hours = parseFloat(row.querySelector<HTMLInputElement>(".service-hours-input")!.value) || 0;
  const service = (appState.settings.services || []).find(s => s.id === serviceId);
  const dateStr = getEarliestSlotDateFromDom();

  let rate = 0;
  if (tarifId === "__custom__") {
    const wrapper = row.closest(".distribution-row-wrapper");
    rate = wrapper ? parseFloat(wrapper.querySelector<HTMLInputElement>(".service-custom-rate-input")!.value) || 0 : 0;
  } else {
    rate = service ? getActiveServiceRate(service, dateStr, tarifId) : 0;
  }

  const hoursInput = row.querySelector<HTMLInputElement>(".service-hours-input")!;
  const isHourly = service && service.type === "hourly";
  hoursInput.style.visibility = isHourly ? "visible" : "hidden";
  const subtotal = isHourly ? rate * hours * count : rate * count;
  row.querySelector<HTMLInputElement>(".service-subtotal-display")!.textContent = formatCurrency(subtotal);
}

export function addFeeRow(
  container: HTMLElement,
  description = "",
  amount: string | number = "",
  glAccountCode = "",
  autoGenerated = false
) {
  const rowId = generateUid("fee-row");

  container.insertAdjacentHTML(
    "beforeend",
    `
    <div id="${rowId}" class="distribution-row" data-auto-generated="${autoGenerated ? "1" : ""}" style="grid-template-columns: 1.5fr 1fr 1.2fr auto auto; align-items: center;">
      <input type="text" id="${rowId}-desc" class="form-input fee-desc-input" value="${escapeHtml(description)}" placeholder="Ex: Montage et démontage" style="padding: 8px 12px; font-size: 0.85rem;">
      <input type="number" id="${rowId}-amount" class="form-input fee-amount-input" min="0" step="0.01" value="${amount !== "" ? amount : ""}" placeholder="Montant $" style="padding: 8px 12px; font-size: 0.85rem;">
      ${buildSearchableSelectHtml("fee-gl-select-wrapper", "fee-gl-select", "Choisir un compte...", `${rowId}-gl`)}
      <div style="display: flex; align-items: center; justify-content: center; min-width: 50px;">
        ${autoGenerated ? `<span class="badge badge-auto" style="white-space: nowrap;" title="Généré automatiquement par l'application">Généré</span>` : ""}
      </div>
      <button type="button" class="btn-icon delete-fee-row-btn" data-row-id="${rowId}">
        <svg viewBox="0 0 24 24" style="width: 14px; height: 14px;"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
      </button>
    </div>
  `
  );

  const row = el(rowId);
  row.querySelector<HTMLInputElement>(".delete-fee-row-btn")!.addEventListener("click", () => {
    row.remove();
    updateSubmissionFinancialSummary();
    autoSaveActivityForm();
  });

  const glItems = appState.settings.accounts.map(acc => ({
    value: acc.code,
    label: `${acc.code} (${acc.description})`
  }));

  initSearchableSelectEl(
    row.querySelector<HTMLElement>(".fee-gl-select-wrapper")!,
    glItems,
    value => {
      updateSubmissionFinancialSummary();
      autoSaveActivityForm();
    },
    glAccountCode
  );

  row.querySelectorAll<HTMLInputElement>(".fee-desc-input, .fee-amount-input")!.forEach(el => {
    el.addEventListener("input", updateSubmissionFinancialSummary);
  });
  rejectNegativeAmountOnBlur(row.querySelector<HTMLInputElement>(".fee-amount-input")!);
}

// Salary id of the default "Directeur technique" entry seeded in config-defaults.ts. Activating
// any "service technique" (Microphone, éclairage, etc.) on a reservation requires a technical
// director on site, so we auto-add one to "Personnel requis" the first time such a service is
// toggled on for that room.
export const TECHNICAL_DIRECTOR_SALARY_ID = "salary-dt";

export function autoAddTechnicalDirectorIfNeeded(staffList: HTMLElement) {
  const salaryExists = (appState.settings.salaries || []).some(s => s.id === TECHNICAL_DIRECTOR_SALARY_ID);
  if (!salaryExists) return;

  const alreadyPresent = Array.from(staffList.querySelectorAll<HTMLSelectElement>(".staff-salary-select")).some(
    sel => sel.value === TECHNICAL_DIRECTOR_SALARY_ID
  );
  if (alreadyPresent) return;

  addStaffRow(staffList, TECHNICAL_DIRECTOR_SALARY_ID, 1, 0, 0, "", true);
}

export function autoAddLinkedStaffAndFees(card: HTMLElement, roomName: string) {
  const room = appState.settings.rooms.find((r: any) => r.name === roomName);
  if (!room) return;

  const staffList = card.querySelector<HTMLInputElement>(".room-staff-list")!;
  (room.linked_staff || []).forEach((s: any) => addStaffRow(staffList, s.salary_id, s.count, 0, 0, "", true));

  const feesList = card.querySelector<HTMLInputElement>(".room-fees-list")!;
  (room.linked_fees || []).forEach((f: any) => addFeeRow(feesList, f.description, f.amount, f.gl_account_code, true));
}

// Rows dropped by collectStaffFromForm/collectServicesFromForm/collectFeesFromForm because they're
// missing their identifier (salary/service/description) but otherwise had data entered (hours,
// count, rate...) would previously disappear silently on save. resetIncompleteRowWarnings() is
// called once per form collection (see collectReservationsFromForm in reservations.ts) so callers
// can warn the user instead.
let incompleteRowWarnings: string[] = [];

export function resetIncompleteRowWarnings() {
  incompleteRowWarnings = [];
}

export function getIncompleteRowWarnings() {
  return incompleteRowWarnings;
}

export function pushIncompleteRowWarning(message: string) {
  incompleteRowWarnings.push(message);
}

export function collectStaffFromForm(card: HTMLElement) {
  const rows = Array.from(card.querySelectorAll<HTMLInputElement>(".room-staff-list .distribution-row")!).map(row => {
    const wrapper = row.closest(".distribution-row-wrapper");
    return {
      id: row.dataset.id || generateUid("staff"),
      salary_id: row.querySelector<HTMLInputElement>(".staff-salary-select")!.value,
      count: parseInt(row.querySelector<HTMLInputElement>(".staff-count-input")!.value, 10) || 0,
      hours: parseFloat(row.querySelector<HTMLInputElement>(".staff-hours-input")!.value) || 0,
      overtime_hours: parseFloat(row.querySelector<HTMLInputElement>(".staff-overtime-hours-input")!.value) || 0,
      tarif_id: row.querySelector<HTMLSelectElement>(".staff-tarif-select")!.value,
      auto_generated: row.dataset.autoGenerated === "1",
      custom_rate: wrapper ? parseFloat(wrapper.querySelector<HTMLInputElement>(".staff-custom-rate-input")!.value) || 0 : 0,
      custom_overtime_rate: wrapper
        ? parseFloat(wrapper.querySelector<HTMLInputElement>(".staff-custom-overtime-rate-input")!.value) || 0
        : 0,
      custom_gl_account_code: wrapper ? wrapper.querySelector<HTMLSelectElement>(".staff-custom-gl-select")!.value : ""
    };
  });
  const dropped = rows.filter(
    s => !s.salary_id && (s.count > 0 || s.hours > 0 || s.overtime_hours > 0 || s.tarif_id || s.custom_rate > 0 || s.custom_overtime_rate > 0)
  );
  if (dropped.length > 0) {
    incompleteRowWarnings.push(
      `${dropped.length} ligne${dropped.length > 1 ? "s" : ""} de personnel sans poste sélectionné n'${dropped.length > 1 ? "ont" : "a"} pas été enregistrée${dropped.length > 1 ? "s" : ""}.`
    );
  }
  return rows.filter(s => s.salary_id);
}

export function collectServicesFromForm(card: HTMLElement) {
  const rows = Array.from(card.querySelectorAll<HTMLInputElement>(".room-services-list .distribution-row")!).map(row => {
    const wrapper = row.closest(".distribution-row-wrapper");
    return {
      id: row.dataset.id || generateUid("service"),
      service_id: row.querySelector<HTMLInputElement>(".service-select")!.value,
      count: parseInt(row.querySelector<HTMLInputElement>(".service-count-input")!.value, 10) || 0,
      hours: parseFloat(row.querySelector<HTMLInputElement>(".service-hours-input")!.value) || 0,
      tarif_id: row.querySelector<HTMLSelectElement>(".service-tarif-select")!.value,
      auto_generated: row.dataset.autoGenerated === "1",
      custom_rate: wrapper ? parseFloat(wrapper.querySelector<HTMLInputElement>(".service-custom-rate-input")!.value) || 0 : 0,
      custom_gl_account_code: wrapper ? wrapper.querySelector<HTMLSelectElement>(".service-custom-gl-select")!.value : ""
    };
  });
  const dropped = rows.filter(s => !s.service_id && (s.count > 0 || s.hours > 0 || s.tarif_id || s.custom_rate > 0));
  if (dropped.length > 0) {
    incompleteRowWarnings.push(
      `${dropped.length} ligne${dropped.length > 1 ? "s" : ""} de service sans service sélectionné n'${dropped.length > 1 ? "ont" : "a"} pas été enregistrée${dropped.length > 1 ? "s" : ""}.`
    );
  }
  return rows.filter(s => s.service_id);
}

export function collectFeesFromForm(card: HTMLElement) {
  const rows = Array.from(card.querySelectorAll<HTMLInputElement>(".room-fees-list .distribution-row")!).map(row => ({
    id: row.dataset.id || generateUid("fee"),
    description: row.querySelector<HTMLInputElement>(".fee-desc-input")!.value.trim(),
    amount: parseFloat(row.querySelector<HTMLInputElement>(".fee-amount-input")!.value) || 0,
    gl_account_code: row.querySelector<HTMLInputElement>(".fee-gl-select-wrapper .searchable-select-value")!.value,
    auto_generated: row.dataset.autoGenerated === "1"
  }));
  const dropped = rows.filter(f => !f.description && (f.amount > 0 || f.gl_account_code));
  if (dropped.length > 0) {
    incompleteRowWarnings.push(
      `${dropped.length} frais sans description n'${dropped.length > 1 ? "ont" : "a"} pas été enregistré${dropped.length > 1 ? "s" : ""}.`
    );
  }
  return rows.filter(f => f.description);
}
