import { appState, getActiveSalaryRate, getActiveSalaryOvertimeRate, getActiveServiceRate } from "../state/state.js";
import { escapeHtml, formatCurrency, generateUid, buildGlAccountOptionsHtml } from "../utils/utils.ts";
import { updateSubmissionFinancialSummary, autoSaveActivityForm } from "./financials.ts";

function el<T extends Element = HTMLInputElement>(id: string): T {
  return document.getElementById(id) as unknown as T;
}

// Helper to query DOM for the earliest slot date to avoid circular dependency
// with activities-reservations.ts's collectReservationsFromForm()
function getEarliestSlotDateFromDom(): string {
  const dates = Array.from(document.querySelectorAll<HTMLInputElement>(".slot-date-input"))
    .map(el => el.value)
    .filter(Boolean)
    .sort();
  return dates[0] || "";
}

export function addStaffRow(container: HTMLElement, salaryId = "", count = 1, hours = 0, overtimeHours = 0, autoGenerated = false) {
  const rowId = generateUid("staff-row");

  const salaryOptionsHtml = (appState.settings.salaries || [])
    .map(s => `<option value="${s.id}" ${s.id === salaryId ? "selected" : ""}>${s.job}</option>`)
    .join("");

  container.insertAdjacentHTML(
    "beforeend",
    `
    <div id="${rowId}" class="distribution-row" data-auto-generated="${autoGenerated ? "1" : ""}" style="grid-template-columns: 1.4fr 0.6fr 0.6fr 0.6fr 1fr auto;">
      <select id="${rowId}-salary" class="select-input staff-salary-select" style="padding: 8px 12px; font-size: 0.85rem;">
        <option value="">Choisir un emploi...</option>
        ${salaryOptionsHtml}
      </select>
      <input type="number" id="${rowId}-count" class="form-input staff-count-input" min="1" step="1" value="${count || 1}" placeholder="Qté" style="padding: 8px 12px; font-size: 0.85rem;">
      <input type="number" id="${rowId}-hours" class="form-input staff-hours-input" min="0" step="0.25" value="${hours || 0}" placeholder="Heures" style="padding: 8px 12px; font-size: 0.85rem;">
      <input type="number" id="${rowId}-overtime-hours" class="form-input staff-overtime-hours-input" min="0" step="0.25" value="${overtimeHours || 0}" placeholder="Heures sup." title="Heures en temps supplémentaire" style="padding: 8px 12px; font-size: 0.85rem;">
      <span class="staff-subtotal-display" style="font-size: 0.85rem; color: var(--text-secondary); align-self: center;">0,00 $</span>
      <button type="button" class="btn-icon delete-staff-row-btn" data-row-id="${rowId}">
        <svg viewBox="0 0 24 24" style="width: 14px; height: 14px;"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
      </button>
    </div>
  `
  );

  const row = el(rowId);
  row.querySelector<HTMLInputElement>(".delete-staff-row-btn")!.addEventListener("click", () => {
    row.remove();
    updateSubmissionFinancialSummary();
    autoSaveActivityForm();
  });
  row.querySelectorAll<HTMLInputElement>("select, input")!.forEach(el => {
    el.addEventListener("input", updateSubmissionFinancialSummary);
    el.addEventListener("change", updateSubmissionFinancialSummary);
  });
  updateStaffRowSubtotal(row);
}

export function updateStaffRowSubtotal(row: HTMLElement) {
  const salaryId = row.querySelector<HTMLInputElement>(".staff-salary-select")!.value;
  const count = parseInt(row.querySelector<HTMLInputElement>(".staff-count-input")!.value, 10) || 0;
  const hours = parseFloat(row.querySelector<HTMLInputElement>(".staff-hours-input")!.value) || 0;
  const overtimeHours = parseFloat(row.querySelector<HTMLInputElement>(".staff-overtime-hours-input")!.value) || 0;
  const salary = (appState.settings.salaries || []).find(s => s.id === salaryId);
  const dateStr = getEarliestSlotDateFromDom();
  const rate = salary ? getActiveSalaryRate(salary, dateStr) : 0;
  const overtimeRate = salary ? getActiveSalaryOvertimeRate(salary, dateStr) : 0;
  row.querySelector<HTMLInputElement>(".staff-subtotal-display")!.textContent = formatCurrency(
    rate * hours * count + overtimeRate * overtimeHours * count
  );
}

export function addServiceRow(container: HTMLElement, serviceId = "", count = 1, hours = 0, autoGenerated = false) {
  const rowId = generateUid("service-row");

  const serviceOptionsHtml = (appState.settings.services || [])
    .map(s => `<option value="${s.id}" ${s.id === serviceId ? "selected" : ""}>${s.name}</option>`)
    .join("");

  container.insertAdjacentHTML(
    "beforeend",
    `
    <div id="${rowId}" class="distribution-row" data-auto-generated="${autoGenerated ? "1" : ""}" style="grid-template-columns: 1.6fr 0.7fr 0.7fr 1fr auto;">
      <select id="${rowId}-service" class="select-input service-select" style="padding: 8px 12px; font-size: 0.85rem;">
        <option value="">Choisir un service...</option>
        ${serviceOptionsHtml}
      </select>
      <input type="number" id="${rowId}-count" class="form-input service-count-input" min="1" step="1" value="${count || 1}" placeholder="Qté" style="padding: 8px 12px; font-size: 0.85rem;">
      <input type="number" id="${rowId}-hours" class="form-input service-hours-input" min="0" step="0.25" value="${hours || 0}" placeholder="Heures" style="padding: 8px 12px; font-size: 0.85rem;">
      <span class="service-subtotal-display" style="font-size: 0.85rem; color: var(--text-secondary); align-self: center;">0,00 $</span>
      <button type="button" class="btn-icon delete-service-row-btn" data-row-id="${rowId}">
        <svg viewBox="0 0 24 24" style="width: 14px; height: 14px;"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
      </button>
    </div>
  `
  );

  const row = el(rowId);
  row.querySelector<HTMLInputElement>(".delete-service-row-btn")!.addEventListener("click", () => {
    row.remove();
    updateSubmissionFinancialSummary();
    autoSaveActivityForm();
  });
  row.querySelectorAll<HTMLInputElement>("select, input")!.forEach(el => {
    el.addEventListener("input", updateSubmissionFinancialSummary);
    el.addEventListener("change", updateSubmissionFinancialSummary);
  });
  updateServiceRowSubtotal(row);
}

export function updateServiceRowSubtotal(row: HTMLElement) {
  const serviceId = row.querySelector<HTMLInputElement>(".service-select")!.value;
  const count = parseInt(row.querySelector<HTMLInputElement>(".service-count-input")!.value, 10) || 0;
  const hours = parseFloat(row.querySelector<HTMLInputElement>(".service-hours-input")!.value) || 0;
  const service = (appState.settings.services || []).find(s => s.id === serviceId);
  const dateStr = getEarliestSlotDateFromDom();
  const rate = service ? getActiveServiceRate(service, dateStr) : 0;
  const hoursInput = row.querySelector<HTMLInputElement>(".service-hours-input")!;
  const isHourly = service && service.type === "hourly";
  hoursInput.style.visibility = isHourly ? "visible" : "hidden";
  const subtotal = isHourly ? rate * hours * count : rate * count;
  row.querySelector<HTMLInputElement>(".service-subtotal-display")!.textContent = formatCurrency(subtotal);
}

export function addFeeRow(
  container: HTMLElement,
  description = "",
  amount: string | number = "",
  glAccountCode = "",
  autoGenerated = false
) {
  const rowId = generateUid("fee-row");

  container.insertAdjacentHTML(
    "beforeend",
    `
    <div id="${rowId}" class="distribution-row" data-auto-generated="${autoGenerated ? "1" : ""}">
      <input type="text" id="${rowId}-desc" class="form-input fee-desc-input" value="${escapeHtml(description)}" placeholder="Ex: Montage et démontage" style="padding: 8px 12px; font-size: 0.85rem;">
      <input type="number" id="${rowId}-amount" class="form-input fee-amount-input" min="0" step="0.01" value="${amount !== "" ? amount : ""}" placeholder="Montant $" style="padding: 8px 12px; font-size: 0.85rem;">
      <select id="${rowId}-gl" class="select-input fee-gl-select" style="padding: 8px 12px; font-size: 0.85rem;">
        ${buildGlAccountOptionsHtml(glAccountCode)}
      </select>
      <button type="button" class="btn-icon delete-fee-row-btn" data-row-id="${rowId}">
        <svg viewBox="0 0 24 24" style="width: 14px; height: 14px;"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
      </button>
    </div>
  `
  );

  const row = el(rowId);
  row.querySelector<HTMLInputElement>(".delete-fee-row-btn")!.addEventListener("click", () => {
    row.remove();
    updateSubmissionFinancialSummary();
    autoSaveActivityForm();
  });
  row.querySelectorAll<HTMLInputElement>("input, select")!.forEach(el => el.addEventListener("input", updateSubmissionFinancialSummary));
}

export function autoAddLinkedStaffAndFees(card: HTMLElement, roomName: string) {
  const room = appState.settings.rooms.find((r: any) => r.name === roomName);
  if (!room) return;

  const staffList = card.querySelector<HTMLInputElement>(".room-staff-list")!;
  (room.linked_staff || []).forEach((s: any) => addStaffRow(staffList, s.salary_id, s.count, 0, 0, true));

  const feesList = card.querySelector<HTMLInputElement>(".room-fees-list")!;
  (room.linked_fees || []).forEach((f: any) => addFeeRow(feesList, f.description, f.amount, f.gl_account_code, true));
}

export function collectStaffFromForm(card: HTMLElement) {
  return Array.from(card.querySelectorAll<HTMLInputElement>(".room-staff-list .distribution-row")!)
    .map(row => ({
      id: row.dataset.id || generateUid("staff"),
      salary_id: row.querySelector<HTMLInputElement>(".staff-salary-select")!.value,
      count: parseInt(row.querySelector<HTMLInputElement>(".staff-count-input")!.value, 10) || 0,
      hours: parseFloat(row.querySelector<HTMLInputElement>(".staff-hours-input")!.value) || 0,
      overtime_hours: parseFloat(row.querySelector<HTMLInputElement>(".staff-overtime-hours-input")!.value) || 0,
      auto_generated: row.dataset.autoGenerated === "1"
    }))
    .filter(s => s.salary_id);
}

export function collectServicesFromForm(card: HTMLElement) {
  return Array.from(card.querySelectorAll<HTMLInputElement>(".room-services-list .distribution-row")!)
    .map(row => ({
      id: row.dataset.id || generateUid("service"),
      service_id: row.querySelector<HTMLInputElement>(".service-select")!.value,
      count: parseInt(row.querySelector<HTMLInputElement>(".service-count-input")!.value, 10) || 0,
      hours: parseFloat(row.querySelector<HTMLInputElement>(".service-hours-input")!.value) || 0,
      auto_generated: row.dataset.autoGenerated === "1"
    }))
    .filter(s => s.service_id);
}

export function collectFeesFromForm(card: HTMLElement) {
  return Array.from(card.querySelectorAll<HTMLInputElement>(".room-fees-list .distribution-row")!)
    .map(row => ({
      id: row.dataset.id || generateUid("fee"),
      description: row.querySelector<HTMLInputElement>(".fee-desc-input")!.value.trim(),
      amount: parseFloat(row.querySelector<HTMLInputElement>(".fee-amount-input")!.value) || 0,
      gl_account_code: row.querySelector<HTMLInputElement>(".fee-gl-select")!.value,
      auto_generated: row.dataset.autoGenerated === "1"
    }))
    .filter(f => f.description);
}
